Add forms function
EasyPost/easypost-go pull request #102
Opened 2022-07-11 18:59 UTC by nwithan8

# Description

- Add functions to create a form for a shipment (with or without additional options, with or without context)
- Add forms unit test and cassette

# Testing

- [x] New unit test for creating a shipment form (with and without options)
- [x] New cassette for unit test
- [x] All tests pass as expected 

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc.)

2022-07-11 19:24 UTC, Justintime50 requested changes

2022-07-11 19:24 UTC, Justintime50 commented on tests/shipment_test.go
> +	assert.NotNil(formType, shipmentWithForm.Forms[0].FormURL)
Issue: I'm unsure how this passed because it's not proper syntax
```suggestion
	assert.NotNil(shipmentWithForm.Forms[0].FormURL)
```

2022-07-11 19:24 UTC, Justintime50 commented on tests/shipment_test.go
> +	assert.NotNil(formType, shipmentWithForm.Forms[0].FormURL)
Issue: I'm unsure how this passed because it's not proper syntax
```suggestion
	assert.NotNil(shipmentWithForm.Forms[0].FormURL)
```

2022-07-11 19:24 UTC, Justintime50 commented on tests/shipment_test.go
> +	assert.Equal(formType, shipmentWithForm.Forms[0].FormType)
Nit: Could assign `shipmentWithForm.Forms[0]` to a variable for easier reuse the 4 times it's used here.

2022-07-12 02:08 UTC, Justintime50 approved these changes

2022-07-12 19:12 UTC, jchen293 approved these changes

2022-07-12 19:22 UTC, merged