Add missing refund functions and fix a typo in Batch
EasyPost/easypost-go pull request #55
Opened 2022-03-01 19:21 UTC by jchen293

This PR adds missing functions in Refund and fixes a typo in the Batch file.

- Add `CreateRefund`, `CreateRefundWithContext`, `ListRefunds`, `ListRefundsWithContext`, `GetRefund`, and `GetRefundWithContext` in the Refund file
- Fix the typo for the `ListBatchesResult` type, change the type from `insurance` to `batch`

2022-03-01 19:23 UTC, Justintime50 commented on batch.go
> +	Batches []*Batch `json:"batches,omitempty"`
Please break the batch changes into a separate PR. PRs should be as small as possible and only contain changes related to one thing. This PR is for the `refund` object and should only have changes related to that.

2022-03-01 19:23 UTC, Justintime50 requested changes
See last comment

2022-03-01 21:35 UTC, Justintime50 approved these changes

2022-03-02 17:03 UTC, nwithan8 approved these changes

2022-03-03 21:45 UTC, merged